import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {newActor,newBattle,emptyStory,parseStory,parseSkills,parsePreset,validateStory,canonicalStory,cardRef} from '../story-core.js';
import {copyProfile,removeProfile,battleSkills,profilePacket} from '../story-skills.js';
const c=JSON.parse(readFileSync(new URL('../data/cards.json',import.meta.url))),decks=JSON.parse(readFileSync(new URL('../data/ai-opponents.json',import.meta.url))).decks;
function fixture(){const a=newActor('a'),b={...newBattle('b'),actor_id:'a',recipe:'DLR_000.ydc'};return {...emptyStory(),actors:[a],battles:[b]};}
test('same character has independent difficulty presets; stable references survive rename',()=>{const d=fixture(),a=d.actors[0];a.skills=[{kind:'lp_bonus',value:1000}];const p=copyProfile(a,'보스',a.skills,'hard');p.skills.push({kind:'opening_draw',value:2});d.battles[0].skill_profile='hard';p.name='최상급';assert.equal(battleSkills(a,d.battles[0]).length,2);assert.equal(a.skills.length,1);assert.equal(parseStory(d).actors[0].skill_profiles[0].name,'최상급');assert.equal(validateStory(d,c.cards,decks).issues.length,0);});
test('deletion is refused while a battle references the profile',()=>{const d=fixture();copyProfile(d.actors[0],'중급',[],'mid');d.battles[0].skill_profile='mid';assert.throws(()=>removeProfile(d,d.actors[0],'mid'));d.battles[0].skill_profile='';removeProfile(d,d.actors[0],'mid');assert.equal(d.actors[0].skill_profiles.length,0);});
test('unknown preset, duplicate IDs and out-of-range draw data fail validation',()=>{const d=fixture();d.battles[0].skill_profile='missing';assert.ok(validateStory(d,c.cards,decks).issues.length);assert.throws(()=>parseSkills([{kind:'opening_draw',value:4}]));assert.throws(()=>parseSkills([{kind:'draw_once',value:2,threshold:0}]));copyProfile(d.actors[0],'a',[],'a');d.actors[0].skill_profiles.push({profile_id:'a',name:'b',skills:[]});assert.throws(()=>parseStory(d));});
test('skill preset JSON round trip clones cards and new skills',()=>{const a=newActor('a'),skills=[{kind:'start_hand',card:cardRef(c.cards.find(x=>!x.special&&x.type==='일반 몬스터'))},{kind:'draw_once',value:2,threshold:2000}];const p=copyProfile(a,'역전',skills,'comeback');const value=parsePreset(profilePacket(a,p));assert.deepEqual(value.skills,skills);value.skills[1].value=3;assert.equal(p.skills[1].value,2);});
test('canonical save rebases cards in every preset and preserves selected battle',()=>{const d=fixture(),card=c.cards.find(x=>!x.special&&x.type==='일반 몬스터');copyProfile(d.actors[0],'초급',[{kind:'start_hand',card:cardRef(card)}],'easy');d.battles[0].skill_profile='easy';const cards=structuredClone(c.cards),next=cards.find(x=>x.slot===card.slot);next.previous_identity_keys=[card.identity_key];next.identity_key='f'.repeat(64);const clean=canonicalStory(d,c.meta,cards);assert.equal(clean.actors[0].skill_profiles[0].skills[0].card.identity_key,next.identity_key);assert.equal(clean.battles[0].skill_profile,'easy');assert.equal(d.actors[0].skill_profiles[0].skills[0].card.identity_key,card.identity_key);});
test('old story JSON round trips without adding new fields or changing progress IDs',()=>{const d=fixture();assert.deepEqual(parseStory(d),d);assert.equal(d.battles[0].battle_id,'b');});
test('starting monster positions survive presets and reject non-monsters',()=>{const d=fixture(),card=c.cards.find(x=>x.slot===1115);for(const position of ['attack','defense','set']){d.actors[0].skills=[{kind:'start_monster',card:cardRef(card),position}];assert.equal(parseStory(d).actors[0].skills[0].position,position);assert.equal(validateStory(d,c.cards,decks).issues.length,0);}d.actors[0].skills[0].position='bad';assert.throws(()=>parseStory(d));d.actors[0].skills[0]={kind:'start_monster',card:cardRef(c.cards.find(x=>x.type==='마법')),position:'attack'};assert.ok(validateStory(d,c.cards,decks).issues.length);});
